# see https://github.com/jameslittle230/stork/blob/master/src/config/mod.rs instead of the official document.
[input]
base_directory="out"
stemming="None"
minimum_indexed_substring_length=2

[[input.files]]
title="android-emulator"
url="/docs/android-emulator"
path="docs/android-emulator.html"

[[input.files]]
title="android-things-raspberry-pi-3"
url="/docs/android-things-raspberry-pi-3"
path="docs/android-things-raspberry-pi-3.html"

[[input.files]]
title="jenkins"
url="/docs/jenkins"
path="docs/jenkins.html"

[[input.files]]
title="sonarqube"
url="/docs/sonarqube"
path="docs/sonarqube.html"

[[input.files]]
title="surfacepro3-recovery"
url="/docs/surfacepro3-recovery"
path="docs/surfacepro3-recovery.html"

[output]
filename="out/blog.st"
