name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash -l -eo pipefail {0}
        env:
          BLOG_MEILISEARCH_API_KEY_CI: ${{ secrets.BLOG_MEILISEARCH_API_KEY_CI }}
          BLOG_MEILISEARCH_API_KEY_SEARCH: ${{ secrets.BLOG_MEILISEARCH_API_KEY_SEARCH }}
          BLOG_MEILISEARCH_BASE_URL: ${{ secrets.BLOG_MEILISEARCH_BASE_URL }}
          BLOG_MEILISEARCH_INDEX_BLOG: ${{ secrets.BLOG_MEILISEARCH_INDEX_BLOG }}
        run: |
          nvm install $(cat .nvmrc)
          nvm use
          mkdir bin
          PATH="$PWD/bin:$PATH"
          curl -L 'https://github.com/rustwasm/wasm-pack/releases/download/v0.11.1/wasm-pack-v0.11.1-x86_64-unknown-linux-musl.tar.gz' | tar -zx --strip-components 1
          mv wasm-pack bin
          npm run docs-parser
          npm run test-docs-parser
          npm ci
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: out
  publish:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master' && github.repository == 'sukawasatoru/blog'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Publish
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler pages publish --project-name blog dist
